// This file is auto-generated by running `npx prisma generate`
// It provides TypeScript types for your database tables

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      meetings: {
        Row: {
          id: string
          title: string
          source_link: string | null
          status: string
          host_id: string
          created_at: string
          updated_at: string | null
        }
        Insert: {
          id?: string
          title: string
          source_link?: string | null
          status?: string
          host_id: string
          created_at?: string
          updated_at?: string | null
        }
        Update: {
          id?: string
          title?: string
          source_link?: string | null
          status?: string
          host_id?: string
          created_at?: string
          updated_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
